/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Cidade;

/**
 *
 * @author igors
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private String pathArquivoEntradaDados;
    private File arquivoEntrada;
    private ArrayList<Cidade> cidades;

    public Principal() {
        initComponents();
        rbSemElitismo.setSelected(true);
        btnProcessar.setEnabled(false);
        cidades = new ArrayList<>();
        txtCapacidadeMamografo.setEnabled(false);
        txtQuantCruzamento.setEnabled(false);
        txtQuantMamografos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        txtCarregar = new javax.swing.JTextField();
        btnCarregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProcessamento = new javax.swing.JTextArea();
        txtQuantMamografos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidadeMamografo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantCruzamento = new javax.swing.JTextField();
        btnProcessar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        rbElitismo = new javax.swing.JRadioButton();
        rbSemElitismo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGs Aplicado na Dist. de Mamógrafos");
        setLocation(new java.awt.Point(450, 180));
        setResizable(false);

        jLabel1.setText("Arquivo de Dados: ");

        txtCarregar.setEnabled(false);

        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        txtProcessamento.setColumns(20);
        txtProcessamento.setRows(5);
        txtProcessamento.setEnabled(false);
        jScrollPane1.setViewportView(txtProcessamento);

        txtQuantMamografos.setText("30");
        txtQuantMamografos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantMamografosKeyTyped(evt);
            }
        });

        jLabel2.setText("Quant. Mamógrafos:*");

        jLabel3.setText("Capacidade do Mamógrafo:*");

        txtCapacidadeMamografo.setText("5069");
        txtCapacidadeMamografo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadeMamografoKeyTyped(evt);
            }
        });

        jLabel4.setText("Quant. Cruzamentos:*");

        txtQuantCruzamento.setText("10");
        txtQuantCruzamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantCruzamentoKeyTyped(evt);
            }
        });

        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        rbElitismo.setText("Com Elitismo");
        rbElitismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbElitismoActionPerformed(evt);
            }
        });

        rbSemElitismo.setText("Sem Elitismo");
        rbSemElitismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSemElitismoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Campos Obrigatórios (*)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Algoritmo Genético Aplicado na Distribuição de Mamógrafos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCarregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcessar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(rbElitismo)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCapacidadeMamografo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtQuantMamografos)
                                    .addComponent(jLabel4)
                                    .addComponent(txtQuantCruzamento)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rbSemElitismo)
                                        .addComponent(jLabel3)))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbElitismo)
                    .addComponent(rbSemElitismo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCapacidadeMamografo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantMamografos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantCruzamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void carregarDados() {
        try {
            // TODO add your handling code here:
            List<String> linhasArquivo = Files.readAllLines(arquivoEntrada.toPath());
            for (String linha : linhasArquivo) {
                String[] fragmentado = linha.split(";");
                int id = Integer.valueOf(fragmentado[0]);
                String nome = fragmentado[1];
                String UF = fragmentado[2];
                int demandaMamografo = Integer.valueOf(fragmentado[3]);
                cidades.add(new Cidade(id, nome, UF, demandaMamografo));
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar o arquivo!", "Algoritmo Genético", JOptionPane.ERROR_MESSAGE, null);
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void exibirDadosIniciais() {
        for (int i = 0; i < cidades.size(); i++) {
            txtProcessamento.setText(txtProcessamento.getText() + "==============\n");
            txtProcessamento.setText(txtProcessamento.getText() + "ID: " + cidades.get(i).getId() + "\n");
            txtProcessamento.setText(txtProcessamento.getText() + "Nome: " + cidades.get(i).getNome() + "\n");
            txtProcessamento.setText(txtProcessamento.getText() + "UF: " + cidades.get(i).getUF() + "\n");
            txtProcessamento.setText(txtProcessamento.getText() + "Demanda: " + cidades.get(i).getDemandaMamografo() + "\n");
            txtProcessamento.setText(txtProcessamento.getText() + "==============\n");
        }
        txtProcessamento.setText(txtProcessamento.getText() + "#=====FIM=====#");
    }

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser file = new JFileChooser();
            file.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int i = file.showSaveDialog(null);
            if (i == 1) {
                txtCarregar.setText("");
            } else {
                arquivoEntrada = file.getSelectedFile();
                txtCarregar.setText(arquivoEntrada.getPath());
                btnProcessar.setEnabled(true);
                txtCapacidadeMamografo.setEnabled(true);
                txtQuantCruzamento.setEnabled(true);
                txtQuantMamografos.setEnabled(true);
                carregarDados();
                exibirDadosIniciais();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar o arquivo!\n" + ex.getMessage(), "Algoritmo Genético", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    private boolean validarCampos() {
        if (txtCapacidadeMamografo.getText().isEmpty()) {
            txtCapacidadeMamografo.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!", "Algoritmo Genético", JOptionPane.WARNING_MESSAGE, null);
            txtCapacidadeMamografo.setBackground(Color.white);
            return false;
        } else if (txtQuantMamografos.getText().isEmpty()) {
            txtQuantMamografos.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!", "Algoritmo Genético", JOptionPane.WARNING_MESSAGE, null);
            txtQuantMamografos.setBackground(Color.white);
            return false;
        } else if (txtQuantCruzamento.getText().isEmpty()) {
            txtQuantCruzamento.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Preencha os campos corretamente!", "Algoritmo Genético", JOptionPane.WARNING_MESSAGE, null);
            txtQuantCruzamento.setBackground(Color.white);
            return false;
        }

        return true;
    }

    private void txtCapacidadeMamografoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadeMamografoKeyTyped
        // TODO add your handling code here:
        boolean teclaCerta = false;
        Character ch = evt.getKeyChar();
        /* aceita números e ponto (.) , por exemplo 12.36, mas não 12,6 */
        if (Character.isDigit(evt.getKeyChar())) {
            teclaCerta = true;
        }
        int comprimentoDeCampo = txtCapacidadeMamografo.getText().length();
        /* se não for um digito ou já houver 20 caracteres no jTextFied o evento é consumido. Nada acontece */
        if (!teclaCerta || comprimentoDeCampo == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCapacidadeMamografoKeyTyped

    private void txtQuantMamografosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantMamografosKeyTyped
        // TODO add your handling code here:
        boolean teclaCerta = false;
        Character ch = evt.getKeyChar();
        /* aceita números e ponto (.) , por exemplo 12.36, mas não 12,6 */
        if (Character.isDigit(evt.getKeyChar())) {
            teclaCerta = true;
        }
        int comprimentoDeCampo = txtQuantMamografos.getText().length();
        /* se não for um digito ou já houver 20 caracteres no jTextFied o evento é consumido. Nada acontece */
        if (!teclaCerta || comprimentoDeCampo == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantMamografosKeyTyped

    private void txtQuantCruzamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantCruzamentoKeyTyped
        // TODO add your handling code here:
        boolean teclaCerta = false;
        Character ch = evt.getKeyChar();
        /* aceita números e ponto (.) , por exemplo 12.36, mas não 12,6 */
        if (Character.isDigit(evt.getKeyChar())) {
            teclaCerta = true;
        }
        int comprimentoDeCampo = txtQuantCruzamento.getText().length();
        /* se não for um digito ou já houver 20 caracteres no jTextFied o evento é consumido. Nada acontece */
        if (!teclaCerta || comprimentoDeCampo == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantCruzamentoKeyTyped

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed

        if (validarCampos()) {
            int capacidadeMamografo = Integer.valueOf(txtCapacidadeMamografo.getText());
            int quantidadeMamografo = Integer.valueOf(txtQuantMamografos.getText());
            int quantidadeCruzamento = Integer.valueOf(txtQuantCruzamento.getText());
            if (rbElitismo.isSelected()) {
                Processando proc = new Processando(cidades, capacidadeMamografo, quantidadeMamografo, quantidadeCruzamento, true);
                proc.setVisible(true);
            } else {
                Processando proc = new Processando(cidades, capacidadeMamografo, quantidadeMamografo, quantidadeCruzamento, false);
                proc.setVisible(true);
            }

        }
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void rbSemElitismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSemElitismoActionPerformed
        // TODO add your handling code here:
        if (rbSemElitismo.isSelected()) {
            rbElitismo.setSelected(false);
        }
    }//GEN-LAST:event_rbSemElitismoActionPerformed

    private void rbElitismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbElitismoActionPerformed
        // TODO add your handling code here:
        if (rbElitismo.isSelected()) {
            rbSemElitismo.setSelected(false);
        }
    }//GEN-LAST:event_rbElitismoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbElitismo;
    private javax.swing.JRadioButton rbSemElitismo;
    private javax.swing.JTextField txtCapacidadeMamografo;
    private javax.swing.JTextField txtCarregar;
    private javax.swing.JTextArea txtProcessamento;
    private javax.swing.JTextField txtQuantCruzamento;
    private javax.swing.JTextField txtQuantMamografos;
    // End of variables declaration//GEN-END:variables
}
